[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[profile.etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

remappings = [
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]